Repository pivotal/docs-tas-adapter, pull requests merged in 2021-12, with the labels that each got.

#6 Added Doc for TBS setup post-install
  install-prerequisites.md
  post-install-tbs-setup.md
Labels: scheduled

#7 Active main
  .gitignore
  README.md
  getting-started.md
  install-prerequisites.md
  install.md
  overview.md
  post-install-tbs-setup.md
  release-notes.md
  supported-cf-cli.md
Labels: in progress

#8 fix tabs in install.md
  install.md
  post-install-tbs-setup.md
Labels: unscheduled

#9 Add instructions for new component scaling
  install.md
Labels: unscheduled

#10 Update Docs for 0.2.0
  install-prerequisites.md
  install.md
Labels: scheduled

#11 Remove manual steps to create service accounts
  getting-started.md
Labels: scheduled

#12 Update supported CLI commands for next beta
  supported-cf-cli.md
Labels: unscheduled
